name: Opt Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  batch-testing:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Generate fuzz
      run: python batch_test.py --timeout=300 --max-procs=32 fuzz ami --num 64

    - name: Fuzz inputs
      run: python batch_test.py --timeout=1200 --max-procs=32 fuzz input --num 8

    - name: Build opts
      run: python batch_test.py --timeout=3600 --max-procs=32 opt --file="passes.opt"

    - name: Test opt correctness
      run: python batch_test.py --timeout=1200 --max-procs=32 run

    - name: Save state on failure
      if: failure()
      run: tar -czvf code.tar.gz code/

    - name: Archive test suite on failure
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: test-suite
        path: code.tar.gz
